# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kingsmandb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate (ORM)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Log de queries no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
