site_name: Documentação

nav:
  - Instruções mkdocs: "index.md"
  - Atas de Reunião:
    - Ata 1: "atas-reuniao/ata-reuniao-1.md"
  - Processo de desenvolvimento: "processo_Desenvolvimento.md"

theme:
  name: material